import type { LocaleCode, ThemeId } from '../../shared/capsule'

// 特效库:每次收到点赞随机选一种,连续两次不会重复
export const HEART_EFFECT_KINDS = [
  'rain',
  'bloom',
  'orbit',
  'wave',
  'shooting',
  'heartbeat',
  'firework',
  'hug',
  'ribbon',
  'gift',
  'cupid',
  'balloon',
  'superlike'
] as const

export type HeartEffectKind = (typeof HEART_EFFECT_KINDS)[number]

// 外观主题:顺序与 THEME_IDS 一致,标签供设置页 SegmentedControl 展示
export const THEME_OPTIONS: ReadonlyArray<{ label: string; value: ThemeId }> = [
  { label: '星夜', value: 'midnight' },
  { label: '极光', value: 'aurora' },
  { label: '赛博', value: 'cyber' },
  { label: '钛金', value: 'titan' },
  { label: '海报', value: 'poster' },
  { label: '孟菲斯', value: 'memphis' },
  { label: '座舱', value: 'cockpit' },
  { label: '宋韵', value: 'inksong' },
  { label: '温室', value: 'greenhouse' },
  { label: '社论', value: 'swiss' }
]

export const COPY = {
  'zh-CN': {
    noData: '无数据',
    refresh: '刷新',
    refreshing: '刷新中',
    source: '来源',
    lastRefresh: '最近刷新',
    settings: '设置',
    details: '详情',
    close: '收起',
    done: '完成',
    back: '返回详情',
    reset: '重置',
    refreshMode: '刷新模式',
    refreshInterval: '刷新间隔',
    customInterval: '自定义秒数',
    custom: '自定义',
    percentageMode: '百分比口径',
    language: '语种',
    launchAtLogin: '开机自启动',
    groupRefresh: '刷新',
    groupDisplay: '显示',
    groupGeneral: '通用',
    groupRegion: '语言与区域',
    auto: '自动',
    manual: '手动',
    enabled: '开启',
    disabled: '关闭',
    remaining: '剩余',
    used: '已使用',
    officialSource: '官方接口',
    localSource: '本地 JSONL',
    emptySource: '无数据',
    officialUnavailable: '官方接口不可用',
    lastRefreshHint: '最近刷新',
    resetExpiry: '到期时间',
    resetCredit: '重置卡',
    today: '今天',
    yesterday: '昨天',
    team: '团队',
    teamBoard: '额度排行榜',
    teamBoardHint: '同组成员按剩余额度降序排名',
    teamModeQuota: '额度',
    teamModeTokens: 'Token消耗',
    teamTokenBoard: 'Token 消耗排行榜',
    teamEmpty: '暂无在线同事,加入团队后会显示同组成员',
    teamSummaryOnline: '在线',
    teamSummaryOnlineUnit: '人',
    teamSummaryAvg: '平均剩余',
    teamSummaryCredits: '重置卡共',
    teamSummaryCreditsUnit: '张',
    teamNickname: '昵称',
    teamNicknameHint: '仅作展示,不涉及凭据',
    teamGroup: '口令',
    teamGroupHint: '同口令的成员才互见',
    teamAnonymous: '未命名成员',
    broadcastEmpty: '暂无消息,发一条让同组同事看到吧',
    broadcastPlaceholder: '发送一条消息,同组成员可见…',
    broadcastSend: '发送',
    broadcastNotInTeam: '未加入团队,设置口令后才能广播',
    broadcastRateLimited: '发送过快,请 2 秒后再试',
    broadcastInvalid: '消息为空或超过 200 字',
    capsuleMessageAria: '广播消息,点击查看消息',
    announcement: '公告',
    announcementAcknowledge: '已知',
    announcementUnread: '未读公告',
    author: '作者',
    version: '版本',
    groupAbout: '关于',
    currentVersion: '当前版本',
    openLogFolder: '打开日志',
    checkUpdate: '检查更新',
    checking: '检查中…',
    upToDate: '已是最新版本',
    newVersionAvailable: '发现新版本',
    downloading: '下载中',
    downloaded: '下载完成',
    installNow: '安装并重启',
    updateError: '更新失败',
    retryUpdate: '重试',
    downloadNow: '立即下载',
    usage: '用量统计',
    usageTotal: '总 Token',
    usageInput: '输入',
    usageOutput: '输出',
    usageCost: '花费',
    usageCached: '缓存',
    usageReasoning: '思考',
    usageCacheHit: '缓存命中',
    usageToday: '今日消耗',
    usageEmpty: '暂无用量数据',
    apiModeSource: 'API Key · 按量计费',
    apiBadge: 'API Key',
    spendReal: '真实账单',
    usage1d: '1天',
    usage7d: '7天',
    usage30d: '30天',
    modelUsage: '模型用量',
    modelOther: '其他',
    rangeCustom: '自定义',
    rangeStart: '开始',
    rangeEnd: '结束',
    rangeApply: '应用',
    usageEstimated: '本地估算',
    groupAgent: '工具',
    agentId: '监控工具',
    agentIdHint: '选择要统计用量与花费的 Agent 工具',
    groupAppearance: '外观',
    theme: '主题',
    themeHint: '切换胶囊与面板的整体风格',
    minimalMode: '极简模式',
    autoKeep5hWindow: '自动保持 5h 窗口',
    windowKeeper: '自动保持 5h 窗口',
    windowKeeperState: '运行状态',
    windowKeeperNextAction: '下次动作时间',
    windowKeeperLastTriggered: '上次成功触发时间',
    windowKeeperRecentError: '最近错误',
    windowKeeperDisabled: '已关闭',
    windowKeeperWaitingData: '等待额度数据',
    windowKeeperWaitingWeeklyReset: '等待周额度恢复',
    windowKeeperWaitingReset: '等待 5h 重置',
    windowKeeperWaitingWindow: '等待 5h 窗口',
    windowKeeperTriggering: '正在触发',
    windowKeeperVerifying: '正在验证额度',
    windowKeeperRetrying: '重试中',
    windowKeeperError: '异常'
  },
  'en-US': {
    noData: 'No data',
    refresh: 'Refresh',
    refreshing: 'Refreshing',
    source: 'Source',
    lastRefresh: 'Last refresh',
    settings: 'Settings',
    details: 'Details',
    close: 'Close',
    done: 'Done',
    back: 'Back to details',
    reset: 'reset',
    refreshMode: 'Refresh mode',
    refreshInterval: 'Refresh interval',
    customInterval: 'Custom seconds',
    custom: 'Custom',
    percentageMode: 'Metric mode',
    language: 'Language',
    launchAtLogin: 'Open at login',
    groupRefresh: 'Refresh',
    groupDisplay: 'Display',
    groupGeneral: 'General',
    groupRegion: 'Language & region',
    auto: 'Auto',
    manual: 'Manual',
    enabled: 'Enabled',
    disabled: 'Disabled',
    remaining: 'Remaining',
    used: 'Used',
    officialSource: 'Official API',
    localSource: 'Local JSONL',
    emptySource: 'No data',
    officialUnavailable: 'Official API unavailable',
    lastRefreshHint: 'Last refresh',
    resetExpiry: 'Expires at',
    resetCredit: 'Reset card',
    today: 'Today',
    yesterday: 'Yesterday',
    team: 'Team',
    teamBoard: 'Quota leaderboard',
    teamBoardHint: 'Sorted by remaining quota, descending',
    teamModeQuota: 'Quota',
    teamModeTokens: 'Tokens',
    teamTokenBoard: 'Token usage',
    teamEmpty: 'No peers online. Join a team to see members.',
    teamSummaryOnline: 'Online',
    teamSummaryOnlineUnit: '',
    teamSummaryAvg: 'Avg remaining',
    teamSummaryCredits: 'Reset cards',
    teamSummaryCreditsUnit: '',
    teamNickname: 'Nickname',
    teamNicknameHint: 'Display only, no credentials shared',
    teamGroup: 'Passphrase',
    teamGroupHint: 'Only peers with the same passphrase can see each other',
    teamAnonymous: 'Unnamed member',
    broadcastEmpty: 'No messages yet — send one to your team',
    broadcastPlaceholder: 'Send a message visible to your team…',
    broadcastSend: 'Send',
    broadcastNotInTeam: 'Not in a team — set a passphrase to broadcast',
    broadcastRateLimited: 'Sending too fast — wait 2s and retry',
    broadcastInvalid: 'Message is empty or exceeds 200 characters',
    capsuleMessageAria: 'Broadcast message, click to view',
    announcement: 'Announcement',
    announcementAcknowledge: 'Got it',
    announcementUnread: 'Unread announcement',
    author: 'Author',
    version: 'Version',
    groupAbout: 'About',
    currentVersion: 'Current version',
    openLogFolder: 'Open log',
    checkUpdate: 'Check for updates',
    checking: 'Checking…',
    upToDate: 'Up to date',
    newVersionAvailable: 'New version available',
    downloading: 'Downloading',
    downloaded: 'Downloaded',
    installNow: 'Install & restart',
    updateError: 'Update failed',
    retryUpdate: 'Retry',
    downloadNow: 'Download',
    usage: 'Usage stats',
    usageTotal: 'Tokens',
    usageInput: 'Input',
    usageOutput: 'Output',
    usageCost: 'Cost',
    usageCached: 'Cached',
    usageReasoning: 'Reasoning',
    usageCacheHit: 'Cache hit',
    usageToday: 'Today used',
    usageEmpty: 'No usage data yet',
    apiModeSource: 'API Key · usage-based',
    apiBadge: 'API Key',
    spendReal: 'Real billing',
    usage1d: '1d',
    usage7d: '7d',
    usage30d: '30d',
    modelUsage: 'Model usage',
    modelOther: 'Other',
    rangeCustom: 'Custom',
    rangeStart: 'Start',
    rangeEnd: 'End',
    rangeApply: 'Apply',
    usageEstimated: 'Estimated',
    groupAgent: 'Agent',
    agentId: 'Agent tool',
    agentIdHint: 'Choose which agent tool to monitor',
    groupAppearance: 'Appearance',
    theme: 'Theme',
    themeHint: 'Switch the overall capsule and panel style',
    minimalMode: 'Minimal mode',
    autoKeep5hWindow: 'Keep 5h window active',
    windowKeeper: 'Keep 5h Window Active',
    windowKeeperState: 'State',
    windowKeeperNextAction: 'Next action',
    windowKeeperLastTriggered: 'Last successful trigger',
    windowKeeperRecentError: 'Recent error',
    windowKeeperDisabled: 'Disabled',
    windowKeeperWaitingData: 'Waiting for quota data',
    windowKeeperWaitingWeeklyReset: 'Waiting for weekly quota reset',
    windowKeeperWaitingReset: 'Waiting for 5h reset',
    windowKeeperWaitingWindow: 'Waiting for 5h window',
    windowKeeperTriggering: 'Triggering',
    windowKeeperVerifying: 'Verifying quota',
    windowKeeperRetrying: 'Retrying',
    windowKeeperError: 'Error'
  }
} as const

export type Copy = (typeof COPY)[LocaleCode]
